---
- hosts: localhost
  vars_files:
    - vars/run-rsync.yml
  tasks:
    - name: "Verify required variables are defined"
      assert:
        that:
          - pvc_data_filepath is defined

    - block:
      - name: "Ensure pvc data file exists"
        stat:
          path: "{{ pvc_data_filepath }}"
        register: p

      - fail:
          msg: "PVC data file from Stage 1 does not exist..."
        when: p.stat.exists == False

      - set_fact:
          pvc_data: "{{ lookup('file', pvc_data_filepath) | from_json }}"
          namespace_data: "{{ lookup('file', namespace_data_filepath) | from_json }}"


    - name: "Create pod and service"
      vars:
        pvc_namespace: "{{ item.namespace }}"
        pod_name: "{{ pvc_namespace }}-rsync"
        svc_name: "{{ pvc_namespace }}-rsync"
        pvcs: "{{ item.pvcs }}"
      include_tasks: "tasks/create-pod-service.yml"
      with_items: "{{ pvc_data }}"
